import "./globals.css";
import Navigation from "./navigation";
import { AuthProvider } from "./context/AuthProvider";
import LocalizationProviderWrapper from "./context/LocalizationProviderWrapper";
import { Container } from "@mui/material";

export const metadata = {
  title: "Portfolio Website Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <LocalizationProviderWrapper>
            <Navigation />
            <Container sx={{padding: "5% 0 5% 0"
            }}>
              {children}
            </Container>
            {/* <div className="container" style={{ padding: "50px 0 50px 0", display: "flex", alignItems: "center", justifyContent: "center", width: "100%" }}> */}
            {/* </div> */}
          </LocalizationProviderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
